name: Test Python

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: satingaux/.github
          token: ${{ secrets.GITHUB_TOKEN }}
        
      
