name: Test Python

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: satingaux/.github
          token: ${{ secrets.GITHUB_TOKEN }}
        
#       - name: Test Python
#         id: testPython
#         uses: satingaux/.github/workflow-templates/actions/test-python@main
#         with:
#           REPO_NAME: ${{ github.event.repository.name }}  
#           PR_TITLE: ${{ github.event.pull_request.title }}
#           PR_NUMBER: ${{ github.event.pull_request.number }}    
#           ACCESS_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
#           USER_NAME: ${{ github.repository }}
#           ACTION_TYPE: ${{ github.event.action }}
#           AUTHOR_NAME: ${{ github.actor }}
